### ISSUE TITLE
Game with Space Exploration won't load after update to 1.18.4

### ISSUE THREAD

**Issue by kryojenik** [Yousei9/Logistic-Train-Network#325]
**Make sure the bug is caused by LTN and not an interface recipient**
Example of a bug in LTN Tracker:
```
 4.581 Error ModManager.cpp:1623: Error while running setup for entity prototype "se-space-elevator-train-stop" (train-stop): Entity must be minable when next_upgrade is set.
```

**Error message or bug description**
Factorio refuses to load after LTN update to 1.18.4 if Space Exploration is also enabled.

**To Reproduce**
Disable all mods except Space Exploration (and dependencies) and LTN, the game will not load.

**LTN version**
X.Y.Z

**Log file**
[factorio-current.log](https://github.com/Yousei9/Logistic-Train-Network/files/12195446/factorio-current.log)

**Comment by kryojenik** [comment]
Nevermind..   #324

**Comment by Yousei9** [comment]
> Seems there are some issues between latest LTN and Cargo Ships

Something else is messing with ports.
Using LTN 1.84.4 with Cargo Ships 0.2.3 works fine.

**Comment by Yousei9** [comment]
duplicate of #324
